### ISSUE TITLE
DTB not convertable by GPL dtc

### ISSUE THREAD

**Issue by evadot** [davidchisnall/dtc#21]
When converting a dtb (converted via this dtc) to a dts with gpl dtc there is a lot of errors : 

<stdout>: ERROR (duplicate_property_names): Duplicate property name fixup in /__local_fixups__

**Comment by davidchisnall** [comment]
Do you have a test case for this? `/local_fixups` should only be generated for plugin compat stuff (`-@`) and the plugin support is relatively new, so I'd be totally unsurprised by bugs.

**Comment by evadot** [comment]
Same as #20 the sun7i-a20-bananapi.dts is what I used.

**Comment by davidchisnall** [comment]
I mean a test case in the Tests directory that is run as part of the regression test suite.

**Comment by evadot** [comment]
No.
This is not a regression in this dtc but an incompatibility with gpl dtc.

**Comment by davidchisnall** [comment]
Yes, but to make sure it is fixed and remains fixed, both this and the PR for #20 need a test case.

**Comment by evadot** [comment]
Yes I'm working on a test case for #20 but I don't have one for this issue as I've not fixed it.

**Comment by davidchisnall** [comment]
Is this still present, and if so any chance of a test case?

**Comment by davidchisnall** [comment]
I believe that this is the same issue as #27 and is now fixed.
